<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = '/home/ec2-user';

return array(
    'phpDocumentor' => array($vendorDir . '/phpdocumentor/reflection-docblock/src'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
);
